// Offline support. Saves the whole game (page, voice clips, fonts, icons) on install so it plays with no internet.
// The page is fetched fresh when online, so updates show up. Bump VERSION when audio, fonts or icons change.
const VERSION = 'animal-game-v1';
const FILES = [
  "./",
  "index.html",
  "manifest.webmanifest",
  "fonts/fonts.css",
  "fonts/andika-400.woff2",
  "fonts/andika-700.woff2",
  "fonts/fredoka-500.woff2",
  "fonts/fredoka-600.woff2",
  "fonts/fredoka-700.woff2",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "audio/a_ant.mp3",
  "audio/a_bear.mp3",
  "audio/a_bee.mp3",
  "audio/a_cat.mp3",
  "audio/a_cow.mp3",
  "audio/a_dog.mp3",
  "audio/a_duck.mp3",
  "audio/a_elephant.mp3",
  "audio/a_fish.mp3",
  "audio/a_fox.mp3",
  "audio/a_frog.mp3",
  "audio/a_goat.mp3",
  "audio/a_hippo.mp3",
  "audio/a_horse.mp3",
  "audio/a_kangaroo.mp3",
  "audio/a_lion.mp3",
  "audio/a_monkey.mp3",
  "audio/a_mouse.mp3",
  "audio/a_octopus.mp3",
  "audio/a_penguin.mp3",
  "audio/a_pig.mp3",
  "audio/a_rabbit.mp3",
  "audio/a_snake.mp3",
  "audio/a_tiger.mp3",
  "audio/a_turtle.mp3",
  "audio/a_whale.mp3",
  "audio/a_zebra.mp3",
  "audio/add_q.mp3",
  "audio/count_pick.mp3",
  "audio/count_q.mp3",
  "audio/done.mp3",
  "audio/l_A.mp3",
  "audio/l_B.mp3",
  "audio/l_C.mp3",
  "audio/l_D.mp3",
  "audio/l_E.mp3",
  "audio/l_F.mp3",
  "audio/l_G.mp3",
  "audio/l_H.mp3",
  "audio/l_K.mp3",
  "audio/l_L.mp3",
  "audio/l_M.mp3",
  "audio/l_O.mp3",
  "audio/l_P.mp3",
  "audio/l_R.mp3",
  "audio/l_S.mp3",
  "audio/l_T.mp3",
  "audio/l_W.mp3",
  "audio/l_Z.mp3",
  "audio/m_add.mp3",
  "audio/m_count.mp3",
  "audio/m_letters.mp3",
  "audio/n1.mp3",
  "audio/n10.mp3",
  "audio/n11.mp3",
  "audio/n12.mp3",
  "audio/n13.mp3",
  "audio/n14.mp3",
  "audio/n15.mp3",
  "audio/n16.mp3",
  "audio/n17.mp3",
  "audio/n18.mp3",
  "audio/n19.mp3",
  "audio/n2.mp3",
  "audio/n20.mp3",
  "audio/n21.mp3",
  "audio/n22.mp3",
  "audio/n23.mp3",
  "audio/n24.mp3",
  "audio/n25.mp3",
  "audio/n3.mp3",
  "audio/n4.mp3",
  "audio/n5.mp3",
  "audio/n6.mp3",
  "audio/n7.mp3",
  "audio/n8.mp3",
  "audio/n9.mp3",
  "audio/plus.mp3",
  "audio/q_ant.mp3",
  "audio/q_bear.mp3",
  "audio/q_bee.mp3",
  "audio/q_cat.mp3",
  "audio/q_cow.mp3",
  "audio/q_dog.mp3",
  "audio/q_duck.mp3",
  "audio/q_elephant.mp3",
  "audio/q_fish.mp3",
  "audio/q_fox.mp3",
  "audio/q_frog.mp3",
  "audio/q_goat.mp3",
  "audio/q_hippo.mp3",
  "audio/q_horse.mp3",
  "audio/q_kangaroo.mp3",
  "audio/q_lion.mp3",
  "audio/q_monkey.mp3",
  "audio/q_mouse.mp3",
  "audio/q_octopus.mp3",
  "audio/q_penguin.mp3",
  "audio/q_pig.mp3",
  "audio/q_rabbit.mp3",
  "audio/q_snake.mp3",
  "audio/q_tiger.mp3",
  "audio/q_turtle.mp3",
  "audio/q_whale.mp3",
  "audio/q_zebra.mp3",
  "audio/together.mp3",
  "audio/try1.mp3",
  "audio/try2.mp3",
  "audio/welcome.mp3",
  "audio/yes1.mp3",
  "audio/yes2.mp3",
  "audio/yes3.mp3",
  "audio/yes4.mp3"
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== VERSION && k.startsWith('animal-game-')).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).then(r => { const copy = r.clone(); caches.open(VERSION).then(c => c.put('index.html', copy)); return r; })
      .catch(() => caches.match('index.html')));
    return;
  }
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req))
  );
});
